---
title: "A Shiny app for Jazz improvisation"
author: "Lucio Cornejo"
date: 2023-07-08
output:
  xaringan::moon_reader:
    css: 
      - default
      - rladies
      - "rladies-fonts"
      - styles.css
    nature:
      highlightStyle: haddock
      highlightLines: true
      countIncrementalSlides: false
      ratio: 16:9
      navigation:
        scroll: false
---

# Who am I?

--

- Mathematics undergraduate from Latin America

--

- Frontend amateur

--

- Shiny enthusiast

--

- .highlight__1[Failed Jazz music player]


---
class: center

# A New Hope

--

<p style="margin-bottom: 20px;"> &nbsp; </p>

<iframe width="560" height="315" src="https://www.youtube.com/embed/-TGIvKZQmGk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>
</iframe>

???
Just show first minute of video.

---

# But ...

--

- .highlight__2[Not free]

--

- .highlight__2[Not for Android]

--

<p style="margin-bottom: 50px;"> &nbsp; </p>

.pull-left[
  # Therefore ...
]

--

.thanos-gif[
<video preload="auto" loop="" autoplay="" width="500" height="300">
<source src="https://media.tenor.com/vCqpL7x4sPUAAAPs/thanos-fine-ill-do-it-myself.webm" type="video/webm">
</video>
]

---
class: center, middle

# [Demo](https://lucio-cornejo.shinyapps.io/jazz-improvisation-app/)

---

# App's basic functionality

<ol id="functionality">
  <li>
    <span>Web scrap chords for popular songs</span>
    <span>Is jazz still popular? :/</span>  
  <li>
    <span>Homogenize chords' notation</span>
    <span>e.g. CM7 = C major 7</span>
  </li>
  <li>
    <span>Detect note played by user</span>
    <span>e.g. using <a href="https://meyda.js.org/">Meyda.js</a></span>
  </li>
  <li>
    <span>Play user selected song</span>
    <span>e.g. using <a href="https://strudel.tidalcycles.org/?C7umG4U5a1Pi">Strudel.js</a></span>
  </li>
  <li>
    <span>Display relationship between selected song and notes played</span>
    <span></span>
  </li>
</ol>

---
class: middle

## Step 1: Web scraping songs

- Code found [here](https://github.com/lucio-cornejo/jazz-improvisation-app/tree/main/web-scraping) .

- Main library used: `Python`'s [BeautifulSoup](https://pypi.org/project/beautifulsoup4/).

- Main database used: [The Jazzomat Research Project](https://jazzomat.hfm-weimar.de/dbformat/dbcontent.html) .

- Final [result](https://github.com/lucio-cornejo/jazz-improvisation-app/blob/main/data/web-scrapped-chord-progressions.json) .

---
class: middle

## Step 2: Homogenize chords' notation

- Chord notation [tranlation](https://github.com/lucio-cornejo/jazz-improvisation-app/blob/main/data/chord-types-translator.json) used .

- [Code](https://github.com/lucio-cornejo/jazz-improvisation-app/blob/main/chord-types/02-translate-chord-types.js) for chord translation .

---
class: middle

## Step 3: Detect note played by user

- `ml5.js`'s note detection module is used.

- [Code](https://github.com/lucio-cornejo/jazz-improvisation-app/blob/main/www/js-main-or-modules/embed-ml5.js)
where `ml5.js` is imported.

- The code for the note detection should be kept isolated,
so that it is easy to replace the tool for note detection
([Pitchy.js](https://github.com/ianprime0509/pitchy), Meyda.js, etc).

---
class: middle

## Step 4: Play user selected song

- `Strudel.js` is being used to produce sound.

- [Code](https://github.com/lucio-cornejo/jazz-improvisation-app/blob/main/www/js-main-or-modules/embed-Strudel.js)
where `Strudel.js` is imported.

- The code for song playing should also be kept isolated, 
for ease of replacement, for example, using [Tone.js](https://tonejs.github.io/).

---
class: middle

## Step 5: Display relationship between selected song and notes played

- Here `Shiny` and basic frontend knowledge comes in handy.

- Example:

(fix css colors for note degrees and put pic here)